import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import BootstrapClient from "../components/BootstrapClient";
import AppLayout from './AppLayout';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ai Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppLayout>
          {children}
        </AppLayout>
        <BootstrapClient /> {/* Add component to the end of the body */}
      </body>
    </html>
  );
}
