import { Geist, Geist_Mono ,Inter } from "next/font/google";
import AppLayout from './AppLayout';
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import BootstrapClient from "@/components/BootstrapClient"; 

const inter = Inter({ subsets: ['latin'] });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ai Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
      <body className={inter.className}>
        <AppLayout>
          <Toaster position="top-right" />
          {children}
        </AppLayout>
        <BootstrapClient /> {/* Add component to the end of the body */}
      </body>
    </html>
  );
}
